### ISSUE TITLE
setup repo to automatically render

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-guide#1]
It'd be nice if, after each push, you could go visit a GH pages or something and see the output, so that people can go read the current contents. If you're interested in doing this, leave a comment! (If you need collaborator status, I can add you.)

**Comment by Michael-F-Bryan** [comment]
[This][1] is what I do for my FFI guide, with this [slightly more complicated][2] one we use for `mdbook` because we need to regenerate CSS and API docs. I'll create a PR which adds a basic `travis.yml` file and the relevant CI stuff.

[1]: https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/ci/deploy.sh
[2]: https://github.com/rust-lang-nursery/mdBook/blob/master/ci/github_pages.sh

**Comment by nikomatsakis** [comment]
@Michael-F-Bryan hmm -- it doesn't quite seem to be working. Any idea what further steps I might have to do? I also added you as a collaborator I think.

**Comment by nikomatsakis** [comment]
Oh, I guess I see the problem:

https://travis-ci.org/rust-lang-nursery/rustc-guide/builds/330775541#L462

`mdbook` command not found

**Comment by nikomatsakis** [comment]
OK, so, @Michael-F-Bryan I did a bunch of setup but now I'm getting weird errors about SSL. Any tips?

https://travis-ci.org/rust-lang-nursery/rustc-guide/builds/332364731#L702

**Comment by nikomatsakis** [comment]
I guess I need some stuff like this:

https://github.com/rust-lang-nursery/mdBook/blob/master/ci/github_pages.sh#L34-L41

**Comment by nikomatsakis** [comment]
Found this handy gist https://gist.github.com/willprice/e07efd73fb7f13f917ea

**Comment by nikomatsakis** [comment]
But there also exists this https://docs.travis-ci.com/user/deployment/pages/ -- which kind of sounds like *exactly* what we want?

**Comment by nikomatsakis** [comment]
Woohoo, a couple of commits later, it seems to be working!
