### ISSUE TITLE
Automated Link Checking

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/rustc-guide#20]
I'm assuming this guide is going to contain lots of links to various bits and pieces around the `rust-lang/rust` repository, so it's probably a good idea to set up some sort of link checking in CI.

I've made a backend for `mdbook` which will read your book and check all the links are valid called [mdbook-linkcheck]. We'll be making another release in the next couple days (rust-lang-nursery/mdBook#558) which will include alternate backends and allow us to use `mdbook-linkcheck` as part of the usual dev process. 

This issue is mostly just a reminder for myself. When the next version of `mdbook` is up on crates.io I'll come back and make a PR including `mdbook-linkcheck` in CI.

[mdbook-linkcheck]: https://github.com/Michael-F-Bryan/mdbook-linkcheck

**Comment by nikomatsakis** [comment]
Yes, this would be great. One of the things I have been wondering is how to link to functions -- or maybe even *snippets* -- in the Rust source. I'd like it if the book were moved into the Rust repository so that changes to the Rust source would not build if they broke the book; but in the meantime, I suppose a "simple" solution would be to have the rustdoc for the compiler posted somewhere, which would give us the ability to link to methods/functions/etc.

**Comment by Michael-F-Bryan** [comment]
I've got a [copy of the internal docs][1] which are recompiled and uploaded daily. Would it be worth asking people to link to that? 

All I did was translate an old shell script of mine into Rust and then set up `cron` to make sure the program gets run while I'm asleep, so if the tool can help here feel free to use/fork it. I remember [talk of making a better solution][2], but I don't think anything came of it.

[1]: https://michael-f-bryan.github.io/rustc-internal-docs/rustc/index.html
[2]: https://github.com/rust-lang/rust/issues/29893#issuecomment-329242784

**Comment by nikomatsakis** [comment]
@Michael-F-Bryan maybe we could put it on rust-lang-nursery or forge or some such?

So long as we are an external guide, of course, we have to think about a policy to detect rot -- i.e., compiler changes, we have to adapt.
